import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
import { Head } from "next/dist/pages/_document";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dias Mashikov Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <Head>
        <link rel="icon" href="public/favicon.ico" />
      </Head> */}
      <body className={`${inter.className} bg-white`}>{children}</body>
    </html>
  );
}
